name: Create Github Release
description: Create a Github Release statement in the project
inputs:
  githubToken:
    required: true
  tag:
    required: true
runs:
  using: "composite"
  steps:      

    # Create Github release
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ inputs.githubToken }}
      with:
        tag_name: ${{ inputs.tag }}
        release_name: ${{ inputs.tag }}
        draft: false
        prerelease: false
