name: Create Github Release
description: Create a Github Release statement in the project
runs:
  using: "composite"
  steps:      

    # Create release on Github
    - name: Get the version
      id: get_version
      run: |
        version=${GITHUB_REF#refs/tags/}
        echo "version=$version" >> $GITHUB_ENV

    # Create Github release
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions
      with:
        tag_name: ${{ steps.get_version.outputs.VERSION }}
        release_name: Release ${{ steps.get_version.outputs.VERSION }}
        draft: false
        prerelease: false
