name: 'Build Web Application'
description: 'Checkout, setup Node.js, install, build, and upload artifacts'
runs:
  using: "composite"
  steps:      
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install and Build
      run: |
        npm ci
        npm run build
      working-directory: ./web
      shell: bash

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifact
        path: |
          web/build/**
          web/infra/**
