name: Deploy Web Application
description: Deploy Web application on AWS Cloud
inputs:
  environment:
    description: Environment
    required: true
  bucketNamePrefix:
    description: Bucket name prefix
    required: true
  roleToAssume:
    description: OIDC role to be assumed
    required: true
  awsRegion:
    required: true
  awsCertificateARN:
    required: true
  domainName:
    required: true
runs:
  using: "composite"
  steps:      

    # AWS Login with OIDC
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: ${{ inputs.roleToAssume }}
        role-session-name: github-action-session
        aws-region: ${{ inputs.awsRegion }}

    # #  Download artifacts to deploy
    # - name: Download artifacts to deploy
    #   uses: actions/download-artifact@v3
    #   with:
    #     name: build-artifact

    # Run IaC (AWS Cloudformation)
    - name: Setup Infrastructe on AWS
      working-directory: ./web/infra/
      shell: bash
      run: |
        chmod +x aws-web-deploy.sh
        ./aws-web-deploy.sh ${{ inputs.environment }} ${{ inputs.domainName }} ${{ inputs.awsCertificateARN }}

    # Deploy web pkg to S3 bucket
    - name: Deploy to S3 bucket
      working-directory: ./web/build/
      shell: bash
      run: |
        aws s3 sync . s3://${{ inputs.bucketNamePrefix }}-${{ inputs.environment }} --delete
